-- Customer & Sales Performance Analysis
-- PostgreSQL analysis of customer behavior, sales performance, and business trends.

-- 1. Data Validation
-- Checks the dataset size, date range, and whether important fields contain missing values.

SELECT COUNT(*) AS total_rows
FROM ecommerce_sales;

SELECT
    MIN(order_date) AS earliest_order,
    MAX(order_date) AS latest_order
FROM ecommerce_sales;

SELECT
    COUNT(*) FILTER (WHERE customer_id IS NULL) AS missing_customer_id,
    COUNT(*) FILTER (WHERE order_date IS NULL) AS missing_order_date,
    COUNT(*) FILTER (WHERE revenue IS NULL) AS missing_revenue,
    COUNT(*) FILTER (WHERE product_category IS NULL) AS missing_category
FROM ecommerce_sales;

-- 2. Overall Business Performance
-- Calculates total orders, unique customers, total revenue, and average order value.

SELECT
    COUNT(DISTINCT order_id) AS total_orders,
    COUNT(DISTINCT customer_id) AS unique_customers,
    ROUND(SUM(revenue), 2) AS total_revenue,
    ROUND(AVG(revenue), 2) AS average_order_value
FROM ecommerce_sales;

-- 3. Product Category Performance
-- Compares total revenue across product categories to identify the strongest-performing categories.

SELECT
    product_category,
    ROUND(SUM(revenue), 2) AS total_revenue
FROM ecommerce_sales
GROUP BY product_category
ORDER BY total_revenue DESC;

-- 4. Top Customers by Lifetime Revenue
-- Identifies the highest-value customers based on total spending, order count, and average order value.

SELECT
    customer_id,
    COUNT(DISTINCT order_id) AS total_orders,
    ROUND(SUM(revenue), 2) AS total_spent,
    ROUND(AVG(revenue), 2) AS average_order_value
FROM ecommerce_sales
GROUP BY customer_id
ORDER BY total_spent DESC
LIMIT 10;

-- 5. Repeat vs One-Time Customers
-- Classifies customers based on whether they placed one order or returned for multiple purchases.

SELECT
    CASE
        WHEN total_orders = 1 THEN 'One-Time Customer'
        ELSE 'Repeat Customer'
    END AS customer_type,
    COUNT(*) AS customer_count
FROM (
    SELECT
        customer_id,
        COUNT(DISTINCT order_id) AS total_orders
    FROM ecommerce_sales
    GROUP BY customer_id
) customer_orders
GROUP BY customer_type;

-- 6. Month-over-Month Revenue Growth
-- Uses a CTE and LAG() window function to compare each month's revenue with the previous month.

WITH monthly_revenue AS (
    SELECT
        DATE_TRUNC('month', order_date) AS month,
        ROUND(SUM(revenue), 2) AS revenue
    FROM ecommerce_sales
    GROUP BY DATE_TRUNC('month', order_date)
)
SELECT
    month,
    revenue,
    LAG(revenue) OVER (ORDER BY month) AS previous_month_revenue,
    ROUND(
        ((revenue - LAG(revenue) OVER (ORDER BY month))
        / LAG(revenue) OVER (ORDER BY month)) * 100,
        2
    ) AS month_over_month_growth_pct
FROM monthly_revenue
ORDER BY month;

-- 7. Customer Segmentation
-- Groups customers into behavioral segments based on total spending and purchase frequency.

WITH customer_summary AS (
    SELECT
        customer_id,
        COUNT(DISTINCT order_id) AS total_orders,
        ROUND(SUM(revenue), 2) AS total_spent,
        MAX(order_date) AS last_order_date
    FROM ecommerce_sales
    GROUP BY customer_id
),
segmented_customers AS (
    SELECT
        customer_id,
        total_orders,
        total_spent,
        last_order_date,
        CASE
            WHEN total_orders >= 8 AND total_spent >= 8000 THEN 'High Value'
            WHEN total_orders >= 5 THEN 'Loyal'
            WHEN total_orders <= 2 THEN 'Low Frequency'
            ELSE 'Regular'
        END AS customer_segment
    FROM customer_summary
)
SELECT
    customer_segment,
    COUNT(*) AS customer_count,
    ROUND(AVG(total_spent), 2) AS avg_customer_spend,
    ROUND(AVG(total_orders), 2) AS avg_orders
FROM segmented_customers
GROUP BY customer_segment
ORDER BY avg_customer_spend DESC;

-- 8. Customer Revenue Concentration
-- Uses cumulative window functions to measure how much total revenue is generated by the highest-spending customers.

WITH customer_revenue AS (
    SELECT
        customer_id,
        SUM(revenue) AS total_revenue
    FROM ecommerce_sales
    GROUP BY customer_id
),
ranked_customers AS (
    SELECT
        customer_id,
        total_revenue,
        SUM(total_revenue) OVER (ORDER BY total_revenue DESC) AS cumulative_revenue,
        SUM(total_revenue) OVER () AS overall_revenue
    FROM customer_revenue
)
SELECT
    customer_id,
    ROUND(total_revenue, 2) AS total_revenue,
    ROUND(cumulative_revenue / overall_revenue * 100, 2) AS cumulative_revenue_pct
FROM ranked_customers
ORDER BY total_revenue DESC;

-- 9. Regional Sales Performance
-- Compares orders, customers, total revenue, and average order value across geographic regions.

SELECT
    region,
    COUNT(DISTINCT order_id) AS total_orders,
    COUNT(DISTINCT customer_id) AS unique_customers,
    ROUND(SUM(revenue), 2) AS total_revenue,
    ROUND(AVG(revenue), 2) AS average_order_value
FROM ecommerce_sales
GROUP BY region
ORDER BY total_revenue DESC;

-- 10. Discount Impact
-- Examines how different discount levels are associated with average revenue and quantity purchased.

SELECT
    discount,
    COUNT(*) AS total_orders,
    ROUND(AVG(revenue), 2) AS avg_revenue,
    ROUND(AVG(quantity), 2) AS avg_quantity
FROM ecommerce_sales
GROUP BY discount
ORDER BY discount;

-- 11. Delivery Performance and Customer Ratings
-- Evaluates whether delivery time is associated with customer ratings or average order revenue.

SELECT
    delivery_days,
    COUNT(*) AS total_orders,
    ROUND(AVG(customer_rating), 2) AS avg_customer_rating,
    ROUND(AVG(revenue), 2) AS avg_revenue
FROM ecommerce_sales
GROUP BY delivery_days
ORDER BY delivery_days;
